version: "3.8"

services:
  backend:
    build: .
    container_name: backend_app
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    restart: always
    ports:
      - "6379:6379"  # Redis main port
      - "8001:8001"  # Redis UI (if needed)
    command: ["redis-server", "--appendonly", "yes"]
